package ai.extime.Enums;

public enum ClipboardEnum {
    NAME, FACEBOOK, INSTAGRAM, LINKEDIN, VK, VIBER, WHATSAPP, TELEGRAM, SKYPE, EMAIL, WEB, PHONE, NOTE, GROUP, ADDRESS, DATEOFBIRTH, POSITION, COMPANY, YOUTUBE, TWITTER, GITHUB, MEDIUM, HASHTAG, G_DOC, G_SHEET, TUMBLR, ANGEL, BIO_INTRO, ZOOM;

}
